### ISSUE TITLE
The url becomes http://localhost:9090/admin/about/__data.json

### ISSUE THREAD

**Issue by devappbox** [munxar/goapi#1]
Hello,

Thank you in advance, what you are doing is very useful.

When adding a file +page.server.js in routes/about folder and clicking about link Everything running well but  the case is the url In console  becomes http://localhost:9090/admin/about/__data.json. 

And if i type  and call  http://localhost:9090/admin/about/ directly in browser, it will display  a link __data.json. 

``````
+page.server.js
/** @type {import('./$types').PageServerLoad} */

export async function load() {
return {}
}

``````
And this doesn't happen if what I add is a +page.js.
 
Hope you to provide me a workaround for this case.

Thank you.

**Comment by munxar** [comment]
Hello

I forgot about this use case. But adding a **trailingSlash: 'always'** in the  **svelte.config.js** should work.

I fixed the codebase: https://github.com/munxar/goapi/commit/abd36fbb935698cfdf51489bd89f9ae9a658db3b

Just a side note: don't fetch from your own api at build time, this is counter what this setup is about. But I see usecases for e.g. fetching an headless cms for embedding documentation.

Hope this solves your problem.

**Comment by devappbox** [comment]
Thank you for your quick response, i really appreciate it. Close by now

**Comment by devappbox** [comment]
After adding this code in +page.server.js
``````
export const actions = {
    default: async () => {
      return {
        success: true
      }
    }
  } satisfies Actions;

``````
it gives me error while building 

``````
Error: Cannot prerender pages with actions
    at render_page (file:///C:/svelte-project/goapi/frontend/.svelte-kit/output/server/index.js:1475:15)
    at async resolve (file:///C:/svelte-project/goapi/frontend/.svelte-kit/output/server/index.js:2169:22)
    at async respond (file:///C:/svelte-project/goapi/frontend/.svelte-kit/output/server/index.js:2206:22)
    at async visit (file:///C:/svelte-project/goapi/frontend/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:201:20)
file:///C:/svelte-project/goapi/frontend/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:30
                                throw new Error(format(details));
                                      ^

Error: 500 /about/ (linked from /about)
    at file:///C:/svelte-project/goapi/frontend/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:30:11
    at save (file:///C:/svelte-project/goapi/frontend/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:358:4)
    at visit (file:///C:/svelte-project/goapi/frontend/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:210:3)

Node.js v18.12.1
[vite-plugin-svelte-kit] Prerendering failed with code 1
error during build:
Error: Prerendering failed with code 1
    at ChildProcess.<anonymous> (file:///C:/svelte-project/goapi/frontend/node_modules/@sveltejs/kit/src/exports/vite/index.js:462:15)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
``````

can you give me insight for this case ?

Thank you in advance

**Comment by devappbox** [comment]
Related topic

https://kit.svelte.dev/docs/page-options#prerender-when-not-to-prerender

https://github.com/sveltejs/kit/issues/7586
